// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASYxPtD-fURogsIPipv2LEJyhr4h7lJyo',
    appId: '1:1097893973643:web:ec9c3e6b90593526bf0e8e',
    messagingSenderId: '1097893973643',
    projectId: 'smartfarm-b6a54',
    authDomain: 'smartfarm-b6a54.firebaseapp.com',
    storageBucket: 'smartfarm-b6a54.appspot.com',
    measurementId: 'G-RQ0PH4CZ5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiFBhGDnrF9NPVwHUOVKPuiSl0oY5Re0w',
    appId: '1:1097893973643:android:3b725d06d621c720bf0e8e',
    messagingSenderId: '1097893973643',
    projectId: 'smartfarm-b6a54',
    storageBucket: 'smartfarm-b6a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbULvBjTxb0gNaKb-t4bQBI8cVG_vodN8',
    appId: '1:1097893973643:ios:b514fe3348f4cdb4bf0e8e',
    messagingSenderId: '1097893973643',
    projectId: 'smartfarm-b6a54',
    storageBucket: 'smartfarm-b6a54.appspot.com',
    iosClientId: '1097893973643-dmj9qs114ttfobdi45ep7iga6fcsi2ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationupdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbULvBjTxb0gNaKb-t4bQBI8cVG_vodN8',
    appId: '1:1097893973643:ios:b514fe3348f4cdb4bf0e8e',
    messagingSenderId: '1097893973643',
    projectId: 'smartfarm-b6a54',
    storageBucket: 'smartfarm-b6a54.appspot.com',
    iosClientId: '1097893973643-dmj9qs114ttfobdi45ep7iga6fcsi2ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationupdate',
  );
}
